appname: sample
port: 9090

db:
    use: postgres
    postgres:
        -   enabled: true
            host: "0.0.0.0"
            port: 5432
            username: "postgres"
            password: "123"
            database: "demo-bamboo"
            nameconn: connPostgres
redis: 
    addr:  "0.0.0.0:6379"
    password: ""
    db:    0

contacts:
    name: 'Javier Lecca'
    email: leccajavier@gmail.com
