appname: sample
port: 9090

db:
    use: postgres
    postgres:
        -   enabled: true
            host: "db"
            port: 5432
            username: "postgres"
            password: "123"
            database: "demo-bamboo"
            nameconn: connPostgres

contacts:
    name: 'Javier Lecca'
    email: leccajavier@gmail.com
